name: pytorch_test

channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - mpi4py=3.0 # installs cuda-aware openmpi
  - pip=20.0
  - python=3.7
  - pytorch=1.5
  - torchvision=0.6